### ISSUE TITLE
history.txt file was not saving the recent mathmatical operation perfrom by end user

### ISSUE THREAD

**Issue by Viddesh1** [WutLolz/-WIP-Calculator-App#1]
Hello @WutLolz,

Thanks for pushing the code to github. :+1: 
I gone through the codebase. You can save the arithmetic calculations in the history.txt file by using below code.

"The issue was you have to close the file after read or write or append etc operations for the respective changes to be reflected in respective file."

If the file is not closed explicitly in this case. I think that after you close the applications explicitly by clicking on close button user interface of tkinter it is iternally taken care by python.

```
# At the 109 number 
history.write(new_line + "\n") # After performing the write operation or read  
history.close() # Make sure to close the file for changes to be updated in the file.
```

Here are few simple implemention of how it work. Method 1 and Method 2 consider them as independent file and test.txt is nothing but sample file that i have copied from history.txt file as for testing perpose.

```
#########################################
# with open(file, mode) as f --> will take care of closing file 
# internally after any read, write operation.

# Method 1:- 

new_line = "2+2=4" 
with open(file="test.txt", mode="a+") as f:
    print(new_line)
    f.write(new_line + "\n")

with open(file="test.txt", mode="r") as ff:
    history_list = []
    for item in ff:
        history_list.append(item.rstrip())

    print(history_list)

########################################

# Method 2:-
new_line = "5*5=25" 

print(new_line)
history = open('test.txt', 'a+')
history.write(new_line + "\n")
# We would need to close the file explicity after any read or write operations.
history.close() 

with open(file="test.txt", mode="r") as ff:
    history_list = []
    for item in ff:
        history_list.append(item.rstrip())

    print(history_list)
```

I hope this helps in resolving your issue. :smile: 

Regards!
Viddesh

**Comment by WutLolz** [comment]
thx

**Comment by Viddesh1** [comment]
Hello,

Closing this issue. As it is already completed.
